language: shell
script:
  - find .dotfiles -type f -name '*.sh' -exec shellcheck --shell=sh --external-sources --exclude=SC2119,SC2120 {} \;
  - |
    find .dotfiles -type f -not -name '*.sh' | while read f;
    do
      if egrep '^#!/usr/bin/env (ba)?sh$' "$f" >/dev/null;
      then
        shellcheck --external-sources "$f" || return 1;
      fi;
    done
