#!/usr/bin/env sh

if command_exists node
then
  node-list-packages() {
    node -e "Object.keys(require('./package')['$1'] || {}).map(function(d) { console.log(d); });"
  }

  node-scripts() {
    node -e "Object.keys(require('./package.json').scripts).map(script => console.log(script))"
  }

  node-run() {
    command="$(if [ -e yarn.lock ]; then echo yarn; else echo 'npm run'; fi)"
    $command $@
  }

  node-dev-script() {
    if node-scripts | grep -q dev
    then
      echo dev
    elif node-scripts | grep -q serve
    then
      echo serve
    else
      echo start
    fi
  }

  node-dev() {
    node-run $(node-dev-script)
  }

  alias dev=node-dev
  alias sb='node-run storybook'

  if command_exists npm
  then
    alias npm-install-latest="sed 's/$/@latest/' | xargs npm install"
    alias npm-upgrade-dep="node-list-packages dependencies | npm-install-latest --save"
    alias npm-upgrade-dev="node-list-packages devDependencies | npm-install-latest --save-dev"
    alias npm-upgrade-peer="node-list-packages peerDependencies | npm-install-latest --save-peer"
    alias npm-upgrade-bundled="node-list-packages bundledDependencies | npm-install-latest --save-bundled"
    alias npm-upgrade-optional="node-list-packages optionalDependencies | npm-install-latest --save-optional"
    alias npm-upgrade="npm-upgrade-dep && npm-upgrade-dev && npm-upgrade-peer && npm-upgrade-bundled && npm-upgrade-optional"
  fi

  if command_exists yarn
  then
    alias yarn-install-latest="sed 's/$/@latest/' | xargs yarn add"
    alias yarn-upgrade-dep="node-list-packages dependencies | yarn-install-latest --save"
    alias yarn-upgrade-dev="node-list-packages devDependencies | yarn-install-latest --save-dev"
    alias yarn-upgrade-peer="node-list-packages peerDependencies | yarn-install-latest --save-peer"
    alias yarn-upgrade-bundled="node-list-packages bundledDependencies | yarn-install-latest --save-bundled"
    alias yarn-upgrade-optional="node-list-packages optionalDependencies | yarn-install-latest --save-optional"
    alias yarn-upgrade="yarn-upgrade-dep && yarn-upgrade-dev && yarn-upgrade-peer && yarn-upgrade-bundled && yarn-upgrade-optional"
  fi
fi
