#!/usr/bin/env bash

RESET='\033[0m'

COLOR_BLACK='\033[0;40;30m'
COLOR_BLACK_LIGHT='\033[1;40;30m'
COLOR_RED='\033[0;40;31m'
COLOR_RED_LIGHT='\033[1;40;31m'
COLOR_GREEN='\033[0;40;32m'
COLOR_GREEN_LIGHT='\033[1;40;32m'
COLOR_YELLOW='\033[0;40;33m'
COLOR_YELLOW_LIGHT='\033[1;40;33m'
COLOR_BLUE='\033[0;40;34m'
COLOR_BLUE_LIGHT='\033[1;40;34m'
COLOR_MAGENTA='\033[0;40;35m'
COLOR_MAGENTA_LIGHT='\033[1;40;35m'
COLOR_CYAN='\033[0;40;36m'
COLOR_CYAN_LIGHT='\033[1;40;36m'
COLOR_WHITE='\033[0;40;37m'
COLOR_WHITE_LIGHT='\033[1;40;37m'

echo -e "${COLOR_BLACK}COLOR_BLACK${RESET}"
echo -e "${COLOR_BLACK_LIGHT}COLOR_BLACK_LIGHT${RESET}"
echo -e "${COLOR_RED}COLOR_RED${RESET}"
echo -e "${COLOR_RED_LIGHT}COLOR_RED_LIGHT${RESET}"
echo -e "${COLOR_GREEN}COLOR_GREEN${RESET}"
echo -e "${COLOR_GREEN_LIGHT}COLOR_GREEN_LIGHT${RESET}"
echo -e "${COLOR_YELLOW}COLOR_YELLOW${RESET}"
echo -e "${COLOR_YELLOW_LIGHT}COLOR_YELLOW_LIGHT${RESET}"
echo -e "${COLOR_BLUE}COLOR_BLUE${RESET}"
echo -e "${COLOR_BLUE_LIGHT}COLOR_BLUE_LIGHT${RESET}"
echo -e "${COLOR_MAGENTA}COLOR_MAGENTA${RESET}"
echo -e "${COLOR_MAGENTA_LIGHT}COLOR_MAGENTA_LIGHT${RESET}"
echo -e "${COLOR_CYAN}COLOR_CYAN${RESET}"
echo -e "${COLOR_CYAN_LIGHT}COLOR_CYAN_LIGHT${RESET}"
echo -e "${COLOR_WHITE}COLOR_WHITE${RESET}"
echo -e "${COLOR_WHITE_LIGHT}COLOR_WHITE_LIGHT${RESET}"

echo "----------------------------------------"

COLOR_UNDERLINE_BLACK='\033[4;40;30m'
COLOR_UNDERLINE_BLACK_LIGHT='\033[1;4;40;30m'
COLOR_UNDERLINE_RED='\033[4;40;31m'
COLOR_UNDERLINE_RED_LIGHT='\033[1;4;40;31m'
COLOR_UNDERLINE_GREEN='\033[4;40;32m'
COLOR_UNDERLINE_GREEN_LIGHT='\033[1;4;40;32m'
COLOR_UNDERLINE_YELLOW='\033[4;40;33m'
COLOR_UNDERLINE_YELLOW_LIGHT='\033[1;4;40;33m'
COLOR_UNDERLINE_BLUE='\033[4;40;34m'
COLOR_UNDERLINE_BLUE_LIGHT='\033[1;4;40;34m'
COLOR_UNDERLINE_MAGENTA='\033[4;40;35m'
COLOR_UNDERLINE_MAGENTA_LIGHT='\033[1;4;40;35m'
COLOR_UNDERLINE_CYAN='\033[4;40;36m'
COLOR_UNDERLINE_CYAN_LIGHT='\033[1;4;40;36m'
COLOR_UNDERLINE_WHITE='\033[4;40;37m'
COLOR_UNDERLINE_WHITE_LIGHT='\033[1;4;40;37m'

echo -e "${COLOR_UNDERLINE_BLACK}COLOR_UNDERLINE_BLACK${RESET}"
echo -e "${COLOR_UNDERLINE_BLACK_LIGHT}COLOR_UNDERLINE_BLACK_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_RED}COLOR_UNDERLINE_RED${RESET}"
echo -e "${COLOR_UNDERLINE_RED_LIGHT}COLOR_UNDERLINE_RED_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_GREEN}COLOR_UNDERLINE_GREEN${RESET}"
echo -e "${COLOR_UNDERLINE_GREEN_LIGHT}COLOR_UNDERLINE_GREEN_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_YELLOW}COLOR_UNDERLINE_YELLOW${RESET}"
echo -e "${COLOR_UNDERLINE_YELLOW_LIGHT}COLOR_UNDERLINE_YELLOW_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_BLUE}COLOR_UNDERLINE_BLUE${RESET}"
echo -e "${COLOR_UNDERLINE_BLUE_LIGHT}COLOR_UNDERLINE_BLUE_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_MAGENTA}COLOR_UNDERLINE_MAGENTA${RESET}"
echo -e "${COLOR_UNDERLINE_MAGENTA_LIGHT}COLOR_UNDERLINE_MAGENTA_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_CYAN}COLOR_UNDERLINE_CYAN${RESET}"
echo -e "${COLOR_UNDERLINE_CYAN_LIGHT}COLOR_UNDERLINE_CYAN_LIGHT${RESET}"
echo -e "${COLOR_UNDERLINE_WHITE}COLOR_UNDERLINE_WHITE${RESET}"
echo -e "${COLOR_UNDERLINE_WHITE_LIGHT}COLOR_UNDERLINE_WHITE_LIGHT${RESET}"

echo "----------------------------------------"

COLOR_BLINKING_BLACK='\033[5;40;30m'
COLOR_BLINKING_BLACK_LIGHT='\033[1;5;40;30m'
COLOR_BLINKING_RED='\033[5;40;31m'
COLOR_BLINKING_RED_LIGHT='\033[1;5;40;31m'
COLOR_BLINKING_GREEN='\033[5;40;32m'
COLOR_BLINKING_GREEN_LIGHT='\033[1;5;40;32m'
COLOR_BLINKING_YELLOW='\033[5;40;33m'
COLOR_BLINKING_YELLOW_LIGHT='\033[1;5;40;33m'
COLOR_BLINKING_BLUE='\033[5;40;34m'
COLOR_BLINKING_BLUE_LIGHT='\033[1;5;40;34m'
COLOR_BLINKING_MAGENTA='\033[5;40;35m'
COLOR_BLINKING_MAGENTA_LIGHT='\033[1;5;40;35m'
COLOR_BLINKING_CYAN='\033[5;40;36m'
COLOR_BLINKING_CYAN_LIGHT='\033[1;5;40;36m'
COLOR_BLINKING_WHITE='\033[5;40;37m'
COLOR_BLINKING_WHITE_LIGHT='\033[1;5;40;37m'

echo -e "${COLOR_BLINKING_BLACK}COLOR_BLINKING_BLACK${RESET}"
echo -e "${COLOR_BLINKING_BLACK_LIGHT}COLOR_BLINKING_BLACK_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_RED}COLOR_BLINKING_RED${RESET}"
echo -e "${COLOR_BLINKING_RED_LIGHT}COLOR_BLINKING_RED_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_GREEN}COLOR_BLINKING_GREEN${RESET}"
echo -e "${COLOR_BLINKING_GREEN_LIGHT}COLOR_BLINKING_GREEN_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_YELLOW}COLOR_BLINKING_YELLOW${RESET}"
echo -e "${COLOR_BLINKING_YELLOW_LIGHT}COLOR_BLINKING_YELLOW_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_BLUE}COLOR_BLINKING_BLUE${RESET}"
echo -e "${COLOR_BLINKING_BLUE_LIGHT}COLOR_BLINKING_BLUE_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_MAGENTA}COLOR_BLINKING_MAGENTA${RESET}"
echo -e "${COLOR_BLINKING_MAGENTA_LIGHT}COLOR_BLINKING_MAGENTA_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_CYAN}COLOR_BLINKING_CYAN${RESET}"
echo -e "${COLOR_BLINKING_CYAN_LIGHT}COLOR_BLINKING_CYAN_LIGHT${RESET}"
echo -e "${COLOR_BLINKING_WHITE}COLOR_BLINKING_WHITE${RESET}"
echo -e "${COLOR_BLINKING_WHITE_LIGHT}COLOR_BLINKING_WHITE_LIGHT${RESET}"

echo "----------------------------------------"

COLOR_INVERTED_BLACK='\033[7;40;30m'
COLOR_INVERTED_BLACK_LIGHT='\033[1;7;40;30m'
COLOR_INVERTED_RED='\033[7;40;31m'
COLOR_INVERTED_RED_LIGHT='\033[1;7;40;31m'
COLOR_INVERTED_GREEN='\033[7;40;32m'
COLOR_INVERTED_GREEN_LIGHT='\033[1;7;40;32m'
COLOR_INVERTED_YELLOW='\033[7;40;33m'
COLOR_INVERTED_YELLOW_LIGHT='\033[1;7;40;33m'
COLOR_INVERTED_BLUE='\033[7;40;34m'
COLOR_INVERTED_BLUE_LIGHT='\033[1;7;40;34m'
COLOR_INVERTED_MAGENTA='\033[7;40;35m'
COLOR_INVERTED_MAGENTA_LIGHT='\033[1;7;40;35m'
COLOR_INVERTED_CYAN='\033[7;40;36m'
COLOR_INVERTED_CYAN_LIGHT='\033[1;7;40;36m'
COLOR_INVERTED_WHITE='\033[7;40;37m'
COLOR_INVERTED_WHITE_LIGHT='\033[1;7;40;37m'

echo -e "${COLOR_INVERTED_BLACK}COLOR_INVERTED_BLACK${RESET}"
echo -e "${COLOR_INVERTED_BLACK_LIGHT}COLOR_INVERTED_BLACK_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_RED}COLOR_INVERTED_RED${RESET}"
echo -e "${COLOR_INVERTED_RED_LIGHT}COLOR_INVERTED_RED_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_GREEN}COLOR_INVERTED_GREEN${RESET}"
echo -e "${COLOR_INVERTED_GREEN_LIGHT}COLOR_INVERTED_GREEN_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_YELLOW}COLOR_INVERTED_YELLOW${RESET}"
echo -e "${COLOR_INVERTED_YELLOW_LIGHT}COLOR_INVERTED_YELLOW_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_BLUE}COLOR_INVERTED_BLUE${RESET}"
echo -e "${COLOR_INVERTED_BLUE_LIGHT}COLOR_INVERTED_BLUE_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_MAGENTA}COLOR_INVERTED_MAGENTA${RESET}"
echo -e "${COLOR_INVERTED_MAGENTA_LIGHT}COLOR_INVERTED_MAGENTA_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_CYAN}COLOR_INVERTED_CYAN${RESET}"
echo -e "${COLOR_INVERTED_CYAN_LIGHT}COLOR_INVERTED_CYAN_LIGHT${RESET}"
echo -e "${COLOR_INVERTED_WHITE}COLOR_INVERTED_WHITE${RESET}"
echo -e "${COLOR_INVERTED_WHITE_LIGHT}COLOR_INVERTED_WHITE_LIGHT${RESET}"

echo "----------------------------------------"

BACKGROUND_BLACK='\033[0;40;30m'
BACKGROUND_RED='\033[0;41;30m'
BACKGROUND_GREEN='\033[0;42;30m'
BACKGROUND_YELLOW='\033[0;43;30m'
BACKGROUND_BLUE='\033[0;44;30m'
BACKGROUND_MAGENTA='\033[0;45;30m'
BACKGROUND_CYAN='\033[0;46;30m'
BACKGROUND_WHITE='\033[0;47;30m'

echo -e "${BACKGROUND_BLACK}BACKGROUND_BLACK${RESET}"
echo -e "${BACKGROUND_RED}BACKGROUND_RED${RESET}"
echo -e "${BACKGROUND_GREEN}BACKGROUND_GREEN${RESET}"
echo -e "${BACKGROUND_YELLOW}BACKGROUND_YELLOW${RESET}"
echo -e "${BACKGROUND_BLUE}BACKGROUND_BLUE${RESET}"
echo -e "${BACKGROUND_MAGENTA}BACKGROUND_MAGENTA${RESET}"
echo -e "${BACKGROUND_CYAN}BACKGROUND_CYAN${RESET}"
echo -e "${BACKGROUND_WHITE}BACKGROUND_WHITE${RESET}"

# echo "----------------------------------------"

# BACKGROUND_INVERTED_BLACK='\033[7;40;30m'
# BACKGROUND_INVERTED_RED='\033[7;41;30m'
# BACKGROUND_INVERTED_GREEN='\033[7;42;30m'
# BACKGROUND_INVERTED_YELLOW='\033[7;43;30m'
# BACKGROUND_INVERTED_BLUE='\033[7;44;30m'
# BACKGROUND_INVERTED_MAGENTA='\033[7;45;30m'
# BACKGROUND_INVERTED_CYAN='\033[7;46;30m'
# BACKGROUND_INVERTED_WHITE='\033[7;47;30m'

# echo -e "${BACKGROUND_INVERTED_BLACK}BACKGROUND_INVERTED_BLACK${RESET}"
# echo -e "${BACKGROUND_INVERTED_RED}BACKGROUND_INVERTED_RED${RESET}"
# echo -e "${BACKGROUND_INVERTED_GREEN}BACKGROUND_INVERTED_GREEN${RESET}"
# echo -e "${BACKGROUND_INVERTED_YELLOW}BACKGROUND_INVERTED_YELLOW${RESET}"
# echo -e "${BACKGROUND_INVERTED_BLUE}BACKGROUND_INVERTED_BLUE${RESET}"
# echo -e "${BACKGROUND_INVERTED_MAGENTA}BACKGROUND_INVERTED_MAGENTA${RESET}"
# echo -e "${BACKGROUND_INVERTED_CYAN}BACKGROUND_INVERTED_CYAN${RESET}"
# echo -e "${BACKGROUND_INVERTED_WHITE}BACKGROUND_INVERTED_WHITE${RESET}"
