#!/usr/bin/env zsh

# Set magic variables for current file & dir
__dir=${0:a:h}
. ${__dir}/../_colors

printf "Normal  \t"
ansi_printf black black ' '
ansi_printf red red ' '
ansi_printf green green ' '
ansi_printf yellow yellow ' '
ansi_printf blue blue ' '
ansi_printf magenta magenta ' '
ansi_printf cyan cyan ' '
ansi_printf white white ' '
ansi_printf gray gray ' '
ansi_printf red_bright red_bright ' '
ansi_printf green_bright green_bright ' '
ansi_printf yellow_bright yellow_bright ' '
ansi_printf blue_bright blue_bright ' '
ansi_printf magenta_bright magenta_bright ' '
ansi_printf cyan_bright cyan_bright ' '
ansi_printf white_bright white_bright '\n'

printf "Bold    \t"
ansi_printf 'bold black' black ' '
ansi_printf 'bold red' red ' '
ansi_printf 'bold green' green ' '
ansi_printf 'bold yellow' yellow ' '
ansi_printf 'bold blue' blue ' '
ansi_printf 'bold magenta' magenta ' '
ansi_printf 'bold cyan' cyan ' '
ansi_printf 'bold white' white ' '
ansi_printf 'bold gray' gray ' '
ansi_printf 'bold red_bright' red_bright ' '
ansi_printf 'bold green_bright' green_bright ' '
ansi_printf 'bold yellow_bright' yellow_bright ' '
ansi_printf 'bold blue_bright' blue_bright ' '
ansi_printf 'bold magenta_bright' magenta_bright ' '
ansi_printf 'bold cyan_bright' cyan_bright ' '
ansi_printf 'bold white_bright' white_bright '\n'

printf "Dim     \t"
ansi_printf 'dim black' black ' '
ansi_printf 'dim red' red ' '
ansi_printf 'dim green' green ' '
ansi_printf 'dim yellow' yellow ' '
ansi_printf 'dim blue' blue ' '
ansi_printf 'dim magenta' magenta ' '
ansi_printf 'dim cyan' cyan ' '
ansi_printf 'dim white' white ' '
ansi_printf 'dim gray' gray ' '
ansi_printf 'dim red_bright' red_bright ' '
ansi_printf 'dim green_bright' green_bright ' '
ansi_printf 'dim yellow_bright' yellow_bright ' '
ansi_printf 'dim blue_bright' blue_bright ' '
ansi_printf 'dim magenta_bright' magenta_bright ' '
ansi_printf 'dim cyan_bright' cyan_bright ' '
ansi_printf 'dim white_bright' white_bright '\n'

printf "Inverse  \t"
ansi_printf 'inverse black' black ' '
ansi_printf 'inverse red' red ' '
ansi_printf 'inverse green' green ' '
ansi_printf 'inverse yellow' yellow ' '
ansi_printf 'inverse blue' blue ' '
ansi_printf 'inverse magenta' magenta ' '
ansi_printf 'inverse cyan' cyan ' '
ansi_printf 'inverse white' white ' '
ansi_printf 'inverse gray' gray ' '
ansi_printf 'inverse red_bright' red_bright ' '
ansi_printf 'inverse green_bright' green_bright ' '
ansi_printf 'inverse yellow_bright' yellow_bright ' '
ansi_printf 'inverse blue_bright' blue_bright ' '
ansi_printf 'inverse magenta_bright' magenta_bright ' '
ansi_printf 'inverse cyan_bright' cyan_bright ' '
ansi_printf 'inverse white_bright' white_bright '\n'

printf "Underline\t"
ansi_printf 'underline black' black ' '
ansi_printf 'underline red' red ' '
ansi_printf 'underline green' green ' '
ansi_printf 'underline yellow' yellow ' '
ansi_printf 'underline blue' blue ' '
ansi_printf 'underline magenta' magenta ' '
ansi_printf 'underline cyan' cyan ' '
ansi_printf 'underline white' white ' '
ansi_printf 'underline gray' gray ' '
ansi_printf 'underline red_bright' red_bright ' '
ansi_printf 'underline green_bright' green_bright ' '
ansi_printf 'underline yellow_bright' yellow_bright ' '
ansi_printf 'underline blue_bright' blue_bright ' '
ansi_printf 'underline magenta_bright' magenta_bright ' '
ansi_printf 'underline cyan_bright' cyan_bright ' '
ansi_printf 'underline white_bright' white_bright '\n'

printf "Italic  \t"
ansi_printf 'italic black' black ' '
ansi_printf 'italic red' red ' '
ansi_printf 'italic green' green ' '
ansi_printf 'italic yellow' yellow ' '
ansi_printf 'italic blue' blue ' '
ansi_printf 'italic magenta' magenta ' '
ansi_printf 'italic cyan' cyan ' '
ansi_printf 'italic white' white ' '
ansi_printf 'italic gray' gray ' '
ansi_printf 'italic red_bright' red_bright ' '
ansi_printf 'italic green_bright' green_bright ' '
ansi_printf 'italic yellow_bright' yellow_bright ' '
ansi_printf 'italic blue_bright' blue_bright ' '
ansi_printf 'italic magenta_bright' magenta_bright ' '
ansi_printf 'italic cyan_bright' cyan_bright ' '
ansi_printf 'italic white_bright' white_bright '\n'

printf "Strikethrough\t"
ansi_printf 'strikethrough black' black ' '
ansi_printf 'strikethrough red' red ' '
ansi_printf 'strikethrough green' green ' '
ansi_printf 'strikethrough yellow' yellow ' '
ansi_printf 'strikethrough blue' blue ' '
ansi_printf 'strikethrough magenta' magenta ' '
ansi_printf 'strikethrough cyan' cyan ' '
ansi_printf 'strikethrough white' white ' '
ansi_printf 'strikethrough gray' gray ' '
ansi_printf 'strikethrough red_bright' red_bright ' '
ansi_printf 'strikethrough green_bright' green_bright ' '
ansi_printf 'strikethrough yellow_bright' yellow_bright ' '
ansi_printf 'strikethrough blue_bright' blue_bright ' '
ansi_printf 'strikethrough magenta_bright' magenta_bright ' '
ansi_printf 'strikethrough cyan_bright' cyan_bright ' '
ansi_printf 'strikethrough white_bright' white_bright '\n'

printf "Hidden  \t"
ansi_printf 'black hidden' black ' '
ansi_printf 'red hidden' red ' '
ansi_printf 'green hidden' green ' '
ansi_printf 'yellow hidden' yellow ' '
ansi_printf 'blue hidden' blue ' '
ansi_printf 'magenta hidden' magenta ' '
ansi_printf 'cyan hidden' cyan ' '
ansi_printf 'white hidden' white ' '
ansi_printf 'gray hidden' gray ' '
ansi_printf 'red_bright hidden' red_bright ' '
ansi_printf 'green_bright hidden' green_bright ' '
ansi_printf 'yellow_bright hidden' yellow_bright ' '
ansi_printf 'blue_bright hidden' blue_bright ' '
ansi_printf 'magenta_bright hidden' magenta_bright ' '
ansi_printf 'cyan_bright hidden' cyan_bright ' '
ansi_printf 'white_bright hidden' white_bright '\n'
