
COLOR_NC='\033[0m' # No Color
COLOR_BLUE='\033[0;34m'
COLOR_LIGHT_BLUE='\033[1;34m'
COLOR_GREEN='\033[0;32m'
COLOR_LIGHT_GREEN='\033[1;32m'
COLOR_CYAN='\033[0;36m'
COLOR_LIGHT_CYAN='\033[1;36m'
COLOR_RED='\033[0;31m'
COLOR_LIGHT_RED='\033[1;31m'
COLOR_PURPLE='\033[0;35m'
COLOR_LIGHT_PURPLE='\033[1;35m'
COLOR_BROWN='\033[0;33m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLACK='\033[0;30m'
COLOR_GRAY='\033[1;30m'
COLOR_LIGHT_GRAY='\033[0;37m'
COLOR_WHITE='\033[1;37m'

echo -e "${COLOR_BLUE}COLOR_BLUE${COLOR_NC}"
echo -e "${COLOR_LIGHT_BLUE}COLOR_LIGHT_BLUE${COLOR_NC}"
echo -e "${COLOR_GREEN}COLOR_GREEN${COLOR_NC}"
echo -e "${COLOR_LIGHT_GREEN}COLOR_LIGHT_GREEN${COLOR_NC}"
echo -e "${COLOR_CYAN}COLOR_CYAN${COLOR_NC}"
echo -e "${COLOR_LIGHT_CYAN}COLOR_LIGHT_CYAN${COLOR_NC}"
echo -e "${COLOR_RED}COLOR_RED${COLOR_NC}"
echo -e "${COLOR_LIGHT_RED}COLOR_LIGHT_RED${COLOR_NC}"
echo -e "${COLOR_PURPLE}COLOR_PURPLE${COLOR_NC}"
echo -e "${COLOR_LIGHT_PURPLE}COLOR_LIGHT_PURPLE${COLOR_NC}"
echo -e "${COLOR_BROWN}COLOR_BROWN${COLOR_NC}"
echo -e "${COLOR_YELLOW}COLOR_YELLOW${COLOR_NC}"
echo -e "${COLOR_BLACK}COLOR_BLACK${COLOR_NC}"
echo -e "${COLOR_GRAY}COLOR_GRAY${COLOR_NC}"
echo -e "${COLOR_LIGHT_GRAY}COLOR_LIGHT_GRAY${COLOR_NC}"
echo -e "COLOR_DEFAULT"
echo -e "${COLOR_WHITE}COLOR_WHITE${COLOR_NC}"
