#!/usr/bin/env sh

if which brew >/dev/null 2>&1; then
  export PATH="/usr/local/bin:$PATH"
  BREW_PATH="$(brew --prefix)/opt"
  export BREW_PATH
fi

brew_exists() {
  [ -d "$BREW_PATH/$1" ] && return 0 || return 1;
}
