#!/usr/bin/env sh

# Open new Terminal tabs from the command line
#
# Author: Justin Hileman (http://justinhileman.com)
#
# Installation:
#     Add the following function to your `.bashrc` or `.bash_profile`,
#     or save it somewhere (e.g. `~/.tab.bash`) and source it in `.bashrc`
#
# Usage:
#     tab                   Opens the current directory in a new tab
#     tab [PATH]            Open PATH in a new tab
#     tab [CMD]             Open a new tab and execute CMD
#     tab [PATH] [CMD] ...  You can prob'ly guess

# Only for teh Mac users
[ "$(uname -s)" != "Darwin" ] && return

tab () {
  cdto="$PWD"
  args="$@"

  if [ -d "$1" ]; then
    cdto=$(cd "$1"; pwd)
    args="${@:2}"
  fi

  osascript &>/dev/null <<EOF
    tell application "System Events"
      tell process "Terminal" to keystroke "t" using command down
    end tell
    tell application "Terminal"
      activate
      do script with command "cd \"$cdto\"; $args" in selected tab of the front window
    end tell
EOF
}
